name: doan_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  carousel_slider: ^5.0.0
  http: ^1.2.0
  path: ^1.8.3
  path_provider: ^2.1.1
  http_interceptor: ^2.0.0
  cached_network_image: ^3.3.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
